# Generated by Django 3.2.8 on 2021-10-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('start', models.DateTimeField(unique=True)),
                ('Duration', models.DurationField()),
                ('end', models.DateField(unique=True)),
            ],
        ),
    ]
